services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    ports:
      - 5500:5500

  my-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'dapp'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - 3306:3306
